carbon-design-system/carbon-for-ibm-dotcom-nextjs-test

- package.json
- pages/_app.js
- yarn.lock
No related issues
This adds meta data that describes what version of the IBM.com Library react and styles packages that are being used.
**New**
- meta tags with package versions on the app wrapper
> feat(version): adds version of packages as meta data

- pages/_app.js
- pages/index.js
- pages/learn.js
- styles/global.scss
- styles/landing.scss
- styles/learn.scss
This switches out the NextJS application to use the discrete style imports for corresponding components/patterns.
**Changed**
- Style imports for IBM.com Library
**Removed**
- Importing all of carbon styles
> fix(styles): switched from global style package to discrete imports

- pages/learn.js
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1617
changed image data property from default to defaultSrc
**New**
- {{new thing}}
**Changed**
```
<LeadSpace
...
],
defaultSrc: 'https://dummyimage.com/1056x480/ee5396/161616',
alt: 'Image alt text',
}}
/>
```
> fix(leadspace-image-mobile-1617): new property name

- styles/learn.scss
Learn Page Template - The spacing between feature card , card with images and cards is too large. [#1654](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/1654)
spacing between card sections is too large, since the components don't have awareness of what other components are on the page, we are going to set the spacing via application level instead
**New**
- add styling to set spacing between card sections
> fix(learn): reduce card section bottom padding

- package.json
- styles/global.scss
- styles/landing.scss
- styles/learn.scss
- yarn.lock
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2267
This fixes a strange issue where the styles package carbon sub dependencies were not getting loaded in properly after a carbon upgrade. Hoping this is a blip, and that adopters will not run into this issue as well. The main fix was to the `yarn.lock` file, but I also added `~` to npm package imports to the project.
**Changed**
- Yarn dependency updates
> fix(yarn): fix to yarn dependencies

- pages/dds-patterns.js
- styles/dds.scss
{{Provide url(s) to the related ticket(s) that this pull request addresses}}
use FeatureCardBlockLarge in solutions page instead of FeatureCard
**Changed**
- Replace `FeatureCard` with `FeatureCardBlockLarge`
> fix(page): use FeatureCardBlockLarge pattern in solutions page

- package.json
- styles/dds.scss
- yarn.lock
Fixes #21
Add missing `ButtonGroup` css import. Also changes `ibmdotcom-react` and `ibmdotcom-styles` package versions to `latest`.
**New**
- `ButtonGroup` css
**Changed**
- `ibmdotcom-react` and `ibmdotcom-styles` packages using `latest` version
> fix(ButtonGroup): add missing style import

- pages/_app.js
- pages/learn.js
{{Provide url(s) to the related ticket(s) that this pull request addresses}}
Add `style` prop to the LinkList component to get the card styles. Also remove unnecessary `heading` prop from the `ContentBlockSimple` cta prop
**Changed**
- remove `heading` prop from `cta`
- add `styles` prop to LinkList
> fix(page): prop updates to linklist and card for learn page

- components/altlang.js
- package.json
- pages/solutions.js
- styles/learn.scss
- yarn.lock
no related issue
This commit changes the titles from lorem ipsum to the component names,
so there is a better understanding of what components are being used
by testers.
In addition, there were some deprecated imports for the Learn page which
was fixed, as well as some React console errors.
**Changed**
- Added `key` index for `altlang`
- Adjusted solution page titles to include the component names
- fixed deprecated style imports for the learn page
> fix(solutions): title fixes for the solution page

- pages/index.js
- pages/services.js
- styles/services.scss
Build Services patterns page in NextJS [#2903](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/2903)
Added LeadSpace component and ContentBlockSegmented pattern to the Services Page
**New**
- LeadSpace
- ContentBlockSegmented
> feat(ServicesPage): added LeadSpace and ContentBlockSegmented

- pages/services.js
- styles/services.scss
Build Services patterns page in NextJS [#2903](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/2903)
Added the third section to the Services page using the ContentBlockCards and CardLink
**Note: CSS is unstable, there is a moment that loads and there is a moment that doesn't.**
Cards on the ContentBlockCards pattern isn't rendering properly, because of this CSS instability
**New**
- ContentBlockCards
- CardLink
> feat(ServicesPage): added ContentBlockCards and CardLink

- pages/services.js
- styles/services.scss
Build Services patterns page in NextJS [#2903](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/2903)
One another section added to Services page, which contains ContentBlockMedia pattern and LinkList, Layout component.
**Note: CSS is unstable, there is a moment that loads and there is a moment that doesn't.**
LinkList component isn't rendering properly, because of this CSS instability
**New**
- Content Block Media
- LinkList
- Layout
> feat(ServicesPage): added ContentBlockMedia, LinkList and Layout

- next.config.js
- package.json
- pages/_app.js
- pages/services.js
https://github.com/carbon-design-system/ibm-dotcom-library/issues/3067
This changes the way that `ibm-common.js` to be dynamically injected after the page has been loaded. Before, changing it to `defer` seems to improve performance, but for some reason scripts are still blocking. 
**Changed**
- Moved `ibm-common.js` from defer to dynamic injection
- Fixed duplicate import issue for `services.scss`
- Put scss and react imports into alphabetical order
> chore(common): moved ibm-common to dynamic injection on page load

- .github/actions/set-dotenv/action.yml
- .github/actions/set-dotenv/index.js
Refs https://github.com/carbon-design-system/ibm-dotcom-library/issues/4098
This adds a missing action script that sets the environment variables in the github action configuration.
**New**
- Github action script for setting .env file
> chore(actions): adding set .env file action for the workflows

- .github/workflows/deploy-ibm-cloud-staging.yml
- .github/workflows/deploy-ibm-cloud.yml
No related issues
This adds a `repository_dispatch` event for this repo to trigger
deployments when NPM canary releases are created
This is an effort to remove these jobs in our other CI builder.
**New**
- `repository_dispatch` event for triggering canary/test builds
**Changed**
- Moved staging builds into its own workflow so it doesn't get triggered by dispatch events
> chore(githubactions): adding repository dispatch events for deployments

- styles/solutions.scss
#4235
Solutions page missing `content-block-cards` styles import
**New**
- import styles to solutions.scss
> fix(content-block-cards): import missing styles

- .github/workflows/deploy-ibm-cloud-staging.yml
This adds in the repository dispatch rule for staging deployment triggers externally.
**Changed**
- `deploy-ibm-cloud-staging.yml `
> chore(staging): adding repository dispatch for staging builds

- pages/solutions.js
[NextJS Page: CTA section - Button is not operable. [Need investigation] #5195](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5195
)
Pass url link to the cta button in `<CTASection />`
**New**
- pass in example link to ctasection button
> fix(solutions): add link to cta section button

- styles/solutions.scss
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6106
The solution page was missing the Callout Quote import, resulting in the proper background color styles not being applied.
**New**
- importing `CalloutQuote` styles
> fix(callout-quote): added missing import

- .github/workflows/deploy-ibm-cloud-staging.yml
- .github/workflows/deploy-ibm-cloud.yml
Per documentation from Github, Ubuntu 16.04 is deprecated. This is upgrading our workflows to 20.04.
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
**Changed**
- Github actions workflow files
> chore(github-actions): upgrade ubuntu to 20.04 for github actions

- .github/workflows/percy-update-base.yml
I noticed that the percy base was not getting triggered, and noticed that the triggers were not configured to listen to the repository dispatch properly.
**Changed**
- percy-update-base.yml
> fix(percy): properly trigger percy base update

- pages/learn.js
- pages/services.js
- pages/solutions.js
React NextJS page: All the images are not loading properly on solution page. [#6691](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6691)
The `:` character in the dummy urls were causing the images to break, replacing `:` with `x` in the text parameter of the url fixes the issue.
**BEFORE:**
**AFTER:**
**Changed**
- change the `:` to `x` in the dummy urls (ie. `https://dummyimage.com/672x378/ee5396/161616&text=16:9` to `https://dummyimage.com/672x378/ee5396/161616&text=16x9`)
> fix(images): replace breaking : character in dummy image urls

- .github/workflows/deploy-ibm-cloud-staging.yml
- .github/workflows/deploy-ibm-cloud.yml
- .github/workflows/percy-update-base.yml
- next.config.js
- pages/services.js
https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/6183
As part of the work deprecating the experimental components, this PR removes all uses of CalloutData and its respective feature flag in the workflows.
**Removed**
- `CalloutData` from the Services page
> chore(housekeeping): remove callout data

- package.json
This will disable video capture in e2e testing by default. This is not necessary to have enabled in our CI runs.
**Changed**
- Disabled video capture in `yarn test:e2e:local`
> test(e2e): disable video capture by default

- .github/workflows/deploy-ibm-cloud-staging.yml
- .github/workflows/deploy-ibm-cloud.yml
Noticed that there were a number of Kaltura calls bombing the g100 page after an e2e test was consistently failing. This might be the cause of it.
Thousands of calls to Kaltura failing:
e2e test failure:
Changing the configuration to use the default IDs may fix this. These IDs are not being set in web components test currently and we are not seeing these issues there.
**Changed**
- Removed configuration of `KALTURA_PARTNER_ID` and `KALTURA_UICONF_ID` in canary, canary RTL, and staging deployments for IBM cloud.
> fix(kaltura): revert setting kaltura env vars to defaults

- tests/e2e/cypress/integration/example-page-a/example-page-a.e2e.js
- tests/e2e/cypress/integration/example-page-b/example-page-b.e2e.js
- tests/e2e/cypress/integration/example-page-c/example-page-c.e2e.js
- tests/e2e/cypress/integration/g100-theme-example/g100-theme-example.e2e.js
- tests/e2e/cypress/integration/white-theme-example/white-theme-example.e2e.js
Refs https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7999
This adds additional waits for elements to load before taking snapshots.
**Changed**
- Add a number of `cy.waitUntil()` to tests
> fix(percy): add additional cy.waitUntil for snapshots
